//#region Group Master
export const GROUPMASTER_INIT = 'modules/groupmaster/GROUPMASTER_INIT';
export const GROUPMASTER_LIST_REQUESTED = 'modules/groupmaster/GROUPMASTER_LIST_REQUESTED';
export const GROUPMASTER_LIST_SUCCESS = 'modules/groupmaster/GROUPMASTER_LIST_SUCCESS';

export const GROUPMASTER_GET_BY_ID_REQUESTED = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_REQUESTED';
export const GROUPMASTER_GET_BY_ID_SUCCESS = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_SUCCESS';
export const GROUPMASTER_GET_BY_ID_ERROR = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_ERROR';

export const GROUPMASTER_DELETE_REQUESTED = 'modules/groupmaster/GROUPMASTER_DELETE_REQUESTED';
export const GROUPMASTER_DELETE_SUCCESS = 'modules/groupmaster/GROUPMASTER_DELETE_SUCCESS';
export const GROUPMASTER_DELETE_ERROR = 'modules/groupmaster/GROUPMASTER_DELETE_ERROR';

export const GROUPMASTER_SAVE_REQUESTED = 'modules/groupmaster/GROUPMASTER_SAVE_REQUESTED';
export const GROUPMASTER_SAVE_SUCCESS = 'modules/groupmaster/GROUPMASTER_SAVE_SUCCESS';
export const GROUPMASTER_SAVE_ERROR = 'modules/groupmaster/GROUPMASTER_SAVE_ERROR';
//#endregion

//#region Alarm Type Master
export const ALARMTYPEMASTER_INIT = 'modules/alarmTyeMaster/ALARMTYPEMASTER_INIT';
export const ALARMTYPEMASTER_LIST_REQUESTED = 'modules/alarmTyeMaster/ALARMTYPEMASTER_LIST_REQUESTED';
export const ALARMTYPEMASTER_LIST_SUCCESS = 'modules/alarmTyeMaster/ALARMTYPEMASTER_LIST_SUCCESS';

export const ALARMTYPEMASTER_GET_BY_ID_REQUESTED = 'modules/alarmTyeMaster/ALARMTYPEMASTER_GET_BY_ID_REQUESTED';
export const ALARMTYPEMASTER_GET_BY_ID_SUCCESS = 'modules/alarmTyeMaster/ALARMTYPEMASTER_GET_BY_ID_SUCCESS';
export const ALARMTYPEMASTER_GET_BY_ID_ERROR = 'modules/alarmTyeMaster/ALARMTYPEMASTER_GET_BY_ID_ERROR';

export const ALARMTYPEMASTER_DELETE_REQUESTED = 'modules/alarmTyeMaster/ALARMTYPEMASTER_DELETE_REQUESTED';
export const ALARMTYPEMASTER_DELETE_SUCCESS = 'modules/alarmTyeMaster/ALARMTYPEMASTER_DELETE_SUCCESS';
export const ALARMTYPEMASTER_DELETE_ERROR = 'modules/alarmTyeMaster/ALARMTYPEMASTER_DELETE_ERROR';

export const ALARMTYPEMASTER_SAVE_REQUESTED = 'modules/alarmTyeMaster/ALARMTYPEMASTER_SAVE_REQUESTED';
export const ALARMTYPEMASTER_SAVE_SUCCESS = 'modules/alarmTyeMaster/ALARMTYPEMASTER_SAVE_SUCCESS';
export const ALARMTYPEMASTER_SAVE_ERROR = 'modules/alarmTyeMaster/ALARMTYPEMASTER_SAVE_ERROR';
//#endregion

//#region Notification Master
export const NOTIFICATIONMASTER_INIT = 'modules/notificationMaster/NOTIFICATIONMASTER_INIT';
export const NOTIFICATIONMASTER_LIST_REQUESTED = 'modules/notificationMaster/NOTIFICATIONMASTER_LIST_REQUESTED';
export const NOTIFICATIONMASTER_LIST_SUCCESS = 'modules/notificationMaster/NOTIFICATIONMASTER_LIST_SUCCESS';

export const NOTIFICATIONMASTER_GET_BY_ID_REQUESTED = 'modules/notificationMaster/NOTIFICATIONMASTER_GET_BY_ID_REQUESTED';
export const NOTIFICATIONMASTER_GET_BY_ID_SUCCESS = 'modules/notificationMaster/NOTIFICATIONMASTER_GET_BY_ID_SUCCESS';
export const NOTIFICATIONMASTER_GET_BY_ID_ERROR = 'modules/notificationMaster/NOTIFICATIONMASTER_GET_BY_ID_ERROR';

export const NOTIFICATIONMASTER_DELETE_REQUESTED = 'modules/notificationMaster/NOTIFICATIONMASTER_DELETE_REQUESTED';
export const NOTIFICATIONMASTER_DELETE_SUCCESS = 'modules/notificationMaster/NOTIFICATIONMASTER_DELETE_SUCCESS';
export const NOTIFICATIONMASTER_DELETE_ERROR = 'modules/notificationMaster/NOTIFICATIONMASTER_DELETE_ERROR';

export const NOTIFICATIONMASTER_SAVE_REQUESTED = 'modules/notificationMaster/NOTIFICATIONMASTER_SAVE_REQUESTED';
export const NOTIFICATIONMASTER_SAVE_SUCCESS = 'modules/notificationMaster/NOTIFICATIONMASTER_SAVE_SUCCESS';
export const NOTIFICATIONMASTER_SAVE_ERROR = 'modules/notificationMaster/NOTIFICATIONMASTER_SAVE_ERROR';
//#endregion

//#region Module Master
export const MODULEMASTER_INIT = 'modules/moduleMaster/MODULEMASTER_INIT';
export const MODULEMASTER_LIST_REQUESTED = 'modules/moduleMaster/MODULEMASTER_LIST_REQUESTED';
export const MODULEMASTER_LIST_SUCCESS = 'modules/moduleMaster/MODULEMASTER_LIST_SUCCESS';

export const MODULEMASTER_GET_BY_ID_REQUESTED = 'modules/moduleMaster/MODULEMASTER_GET_BY_ID_REQUESTED';
export const MODULEMASTER_GET_BY_ID_SUCCESS = 'modules/moduleMaster/MODULEMASTER_GET_BY_ID_SUCCESS';
export const MODULEMASTER_GET_BY_ID_ERROR = 'modules/moduleMaster/MODULEMASTER_GET_BY_ID_ERROR';

export const MODULEMASTER_DELETE_REQUESTED = 'modules/moduleMaster/MODULEMASTER_DELETE_REQUESTED';
export const MODULEMASTER_DELETE_SUCCESS = 'modules/moduleMaster/MODULEMASTER_DELETE_SUCCESS';
export const MODULEMASTER_DELETE_ERROR = 'modules/moduleMaster/MODULEMASTER_DELETE_ERROR';

export const MODULEMASTER_SAVE_REQUESTED = 'modules/moduleMaster/MODULEMASTER_SAVE_REQUESTED';
export const MODULEMASTER_SAVE_SUCCESS = 'modules/moduleMaster/MODULEMASTER_SAVE_SUCCESS';
export const MODULEMASTER_SAVE_ERROR = 'modules/moduleMaster/MODULEMASTER_SAVE_ERROR';
//#endregion

//#region Org Relation Type Master
export const ORGRELATIONTYPEMASTER_INIT = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_INIT';
export const ORGRELATIONTYPEMASTER_LIST_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_LIST_REQUESTED';
export const ORGRELATIONTYPEMASTER_LIST_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_LIST_SUCCESS';

export const ORGRELATIONTYPEMASTER_GET_BY_ID_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_REQUESTED';
export const ORGRELATIONTYPEMASTER_GET_BY_ID_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_SUCCESS';
export const ORGRELATIONTYPEMASTER_GET_BY_ID_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_ERROR';

export const ORGRELATIONTYPEMASTER_DELETE_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_REQUESTED';
export const ORGRELATIONTYPEMASTER_DELETE_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_SUCCESS';
export const ORGRELATIONTYPEMASTER_DELETE_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_ERROR';

export const ORGRELATIONTYPEMASTER_SAVE_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_REQUESTED';
export const ORGRELATIONTYPEMASTER_SAVE_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_SUCCESS';
export const ORGRELATIONTYPEMASTER_SAVE_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_ERROR';
//#endregion

//#region Role Master
export const ROLEMASTER_INIT = 'modules/rolemaster/ROLEMASTER_INIT';
export const ROLEMASTER_LIST_REQUESTED = 'modules/rolemaster/ROLEMASTER_LIST_REQUESTED';
export const ROLEMASTER_LIST_SUCCESS = 'modules/rolemaster/ROLEMASTER_LIST_SUCCESS';

export const ROLEMASTER_GET_BY_ID_REQUESTED = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_REQUESTED';
export const ROLEMASTER_GET_BY_ID_SUCCESS = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_SUCCESS';
export const ROLEMASTER_GET_BY_MODULEID_SUCCESS = 'modules/rolemaster/ROLEMASTER_GET_BY_MODULEID_SUCCESS';
export const ROLEMASTER_GET_BY_ID_ERROR = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_ERROR';

export const ROLEMASTER_DELETE_REQUESTED = 'modules/rolemaster/ROLEMASTER_DELETE_REQUESTED';
export const ROLEMASTER_DELETE_SUCCESS = 'modules/rolemaster/ROLEMASTER_DELETE_SUCCESS';
export const ROLEMASTER_DELETE_ERROR = 'modules/rolemaster/ROLEMASTER_DELETE_ERROR';

export const ROLEMASTER_SAVE_REQUESTED = 'modules/rolemaster/ROLEMASTER_SAVE_REQUESTED';
export const ROLEMASTER_SAVE_SUCCESS = 'modules/rolemaster/ROLEMASTER_SAVE_SUCCESS';
export const ROLEMASTER_SAVE_ERROR = 'modules/rolemaster/ROLEMASTER_SAVE_ERROR';
//#endregion

//#region Group Company Master
export const COMPANYMASTER_INIT = 'modules/companymaster/COMPANYMASTER_INIT';
export const COMPANYMASTER_LIST_REQUESTED = 'modules/companymaster/COMPANYMASTER_LIST_REQUESTED';
export const COMPANYMASTER_LIST_SUCCESS = 'modules/companymaster/COMPANYMASTER_LIST_SUCCESS';

export const COMPANYMASTER_GET_BY_ID_REQUESTED = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_REQUESTED';
export const COMPANYMASTER_GET_BY_ID_SUCCESS = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_SUCCESS';
export const COMPANYMASTER_GET_BY_GROUPID_SUCCESS = 'modules/companymaster/COMPANYMASTER_GET_BY_GROUPID_SUCCESS';
export const COMPANYMASTER_GET_BY_ID_ERROR = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_ERROR';

export const COMPANYMASTER_DELETE_REQUESTED = 'modules/companymaster/COMPANYMASTER_DELETE_REQUESTED';
export const COMPANYMASTER_DELETE_SUCCESS = 'modules/companymaster/COMPANYMASTER_DELETE_SUCCESS';
export const COMPANYMASTER_DELETE_ERROR = 'modules/companymaster/COMPANYMASTER_DELETE_ERROR';

export const COMPANYMASTER_SAVE_REQUESTED = 'modules/companymaster/COMPANYMASTER_SAVE_REQUESTED';
export const COMPANYMASTER_SAVE_SUCCESS = 'modules/companymaster/COMPANYMASTER_SAVE_SUCCESS';
export const COMPANYMASTER_SAVE_ERROR = 'modules/companymaster/COMPANYMASTER_SAVE_ERROR';
//#endregion
 
//#region User Master
export const USER_INIT = 'modules/usermaster/USER_INIT';
export const USER_LIST_REQUESTED = 'modules/usermaster/USER_LIST_REQUESTED';
export const USER_LIST_SUCCESS = 'modules/usermaster/USER_LIST_SUCCESS';

export const USER_GET_BY_ID_REQUESTED = 'modules/usermaster/USER_GET_BY_ID_REQUESTED';
export const USER_GET_BY_ID_SUCCESS = 'modules/usermaster/USER_GET_BY_ID_SUCCESS';
export const USER_GET_BY_PLANTID_SUCCESS = 'modules/usermaster/USER_GET_BY_PLANTID_SUCCESS';
export const USER_GET_BY_PLANTDEPARTMENTID_SUCCESS = 'modules/usermaster/USER_GET_BY_PLANTDEPARTMENTID_SUCCESS';
export const USER_GET_BY_ID_ERROR = 'modules/usermaster/USER_GET_BY_ID_ERROR';

export const USER_DELETE_REQUESTED = 'modules/usermaster/USER_DELETE_REQUESTED';
export const USER_DELETE_SUCCESS = 'modules/usermaster/USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'modules/usermaster/USER_DELETE_ERROR';

export const USER_SAVE_REQUESTED = 'modules/usermaster/USER_SAVE_REQUESTED';
export const USER_SAVE_SUCCESS = 'modules/usermaster/USER_SAVE_SUCCESS';
export const USER_SAVE_ERROR = 'modules/usermaster/USER_SAVE_ERROR';
export const USER_GET_BY_GROUPID_SUCCESS = 'modules/usermaster/USER_GET_BY_GROUPID_SUCCESS';
//#endregion

//#region Year Master
export const YEARMASTER_INIT = 'modules/yearmaster/YEARMASTER_INIT';
export const YEARMASTER_LIST_REQUESTED = 'modules/yearmaster/YEARMASTER_LIST_REQUESTED';
export const YEARMASTER_LIST_SUCCESS = 'modules/yearmaster/YEARMASTER_LIST_SUCCESS';

//#endregion

//#region Notification  Details
export const NOTIFICATIONMASTERDETAILS_INIT = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_INIT';
export const NOTIFICATIONMASTERDETAILS_LIST_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_LIST_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_LIST_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_LIST_SUCCESS';

export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_ERROR';

export const NOTIFICATIONMASTERDETAILS_DELETE_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_DELETE_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_DELETE_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_ERROR';

export const NOTIFICATIONMASTERDETAILS_SAVE_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_SAVE_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_SAVE_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_ERROR';
//#endregion

//#region Country Master
export const COUNTRYMASTER_INIT = 'modules/countrymaster/COUNTRYMASTER_INIT';
export const COUNTRYMASTER_LIST_REQUESTED = 'modules/countrymaster/COUNTRYMASTER_LIST_REQUESTED';
export const COUNTRYMASTER_LIST_SUCCESS = 'modules/countrymaster/COUNTRYMASTER_LIST_SUCCESS';
//#endregion

//#region State Master
export const STATEMASTER_INIT = 'modules/statemaster/STATEMASTER_INIT';
export const STATEMASTER_LIST_REQUESTED = 'modules/statemaster/STATEMASTER_LIST_REQUESTED';
export const STATEMASTER_LIST_SUCCESS = 'modules/statemaster/STATEMASTER_LIST_SUCCESS';
//#endregion

//#region City Master
export const CITYMASTER_INIT = 'modules/citymaster/CITYMASTER_INIT';
export const CITYMASTER_LIST_REQUESTED = 'modules/citymaster/CITYMASTER_LIST_REQUESTED';
export const CITYMASTER_LIST_SUCCESS = 'modules/citymaster/CITYMASTER_LIST_SUCCESS';
//#endregion

//#region Gender Master
export const GENDERMASTER_INIT = 'modules/gendermaster/GENDERMASTER_INIT';
export const GENDERMASTER_LIST_REQUESTED = 'modules/gendermaster/GENDERMASTER_LIST_REQUESTED';
export const GENDERMASTER_LIST_SUCCESS = 'modules/gendermaster/GENDERMASTER_LIST_SUCCESS';
//#endregion

//#region Organisation Master
export const ORGANISATIONDETAILS_INIT = 'modules/organisationdetails/ORGANISATIONDETAILS_INIT';
export const ORGANISATIONDETAILS_LIST_REQUESTED = 'modules/organisationdetails/ORGANISATIONDETAILS_LIST_REQUESTED';
export const ORGANISATIONDETAILS_LIST_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_LIST_SUCCESS';

export const ORGANISATIONDETAILS_GET_BY_ID_REQUESTED = 'modules/organisationdetails/ORGANISATIONDETAILS_GET_BY_ID_REQUESTED';
export const ORGANISATIONDETAILS_GET_BY_ID_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_GET_BY_ID_SUCCESS';
export const ORGANISATIONDETAILS_GET_BY_GROUPID_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_GET_BY_GROUPID_SUCCESS';
export const ORGANISATIONDETAILS_GET_BY_ORGRELATIONTYPEID_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_GET_BY_ORGRELATIONTYPEID_SUCCESS';
export const ORGANISATIONDETAILS_GET_BY_ID_ERROR = 'modules/organisationdetails/ORGANISATIONDETAILS_GET_BY_ID_ERROR';

export const ORGANISATIONDETAILS_DELETE_REQUESTED = 'modules/organisationdetails/ORGANISATIONDETAILS_DELETE_REQUESTED';
export const ORGANISATIONDETAILS_DELETE_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_DELETE_SUCCESS';
export const ORGANISATIONDETAILS_DELETE_ERROR = 'modules/organisationdetails/ORGANISATIONDETAILS_DELETE_ERROR';

export const ORGANISATIONDETAILS_SAVE_REQUESTED = 'modules/organisationdetails/ORGANISATIONDETAILS_SAVE_REQUESTED';
export const ORGANISATIONDETAILS_SAVE_SUCCESS = 'modules/organisationdetails/ORGANISATIONDETAILS_SAVE_SUCCESS';
export const ORGANISATIONDETAILS_SAVE_ERROR = 'modules/organisationdetails/ORGANISATIONDETAILS_SAVE_ERROR';
//#endregion

//#region Organisation Employee Master
export const ORGANISATIONEMPLOYEEDETAILS_INIT = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_INIT';
export const ORGANISATIONEMPLOYEEDETAILS_LIST_REQUESTED = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_LIST_REQUESTED';
export const ORGANISATIONEMPLOYEEDETAILS_LIST_SUCCESS = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_LIST_SUCCESS';

export const ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_REQUESTED = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_REQUESTED';
export const ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_SUCCESS = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_SUCCESS';
export const ORGANISATIONEMPLOYEEDETAILS_GET_BY_ORGDETAILSID_SUCCESS = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_GET_BY_ORGDETAILSID_SUCCESS';
export const ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_ERROR = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_GET_BY_ID_ERROR';

export const ORGANISATIONEMPLOYEEDETAILS_DELETE_REQUESTED = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_DELETE_REQUESTED';
export const ORGANISATIONEMPLOYEEDETAILS_DELETE_SUCCESS = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_DELETE_SUCCESS';
export const ORGANISATIONEMPLOYEEDETAILS_DELETE_ERROR = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_DELETE_ERROR';

export const ORGANISATIONEMPLOYEEDETAILS_SAVE_REQUESTED = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_SAVE_REQUESTED';
export const ORGANISATIONEMPLOYEEDETAILS_SAVE_SUCCESS = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_SAVE_SUCCESS';
export const ORGANISATIONEMPLOYEEDETAILS_SAVE_ERROR = 'modules/organisationdetails/ORGANISATIONEMPLOYEEDETAILS_SAVE_ERROR';

//#endregion

// //#region Tower Master
// export const TOWERMASTER_INIT = 'modules/towerMaster/TOWERMASTER_INIT';
// export const TOWERMASTER_LIST_REQUESTED = 'modules/towerMaster/TOWERMASTER_LIST_REQUESTED';
// export const TOWERMASTER_LIST_SUCCESS = 'modules/towerMaster/TOWERMASTER_LIST_SUCCESS';

// export const TOWERMASTER_GET_BY_ID_REQUESTED = 'modules/towerMaster/TOWERMASTER_GET_BY_ID_REQUESTED';
// export const TOWERMASTER_GET_BY_ID_SUCCESS = 'modules/towerMaster/TOWERMASTER_GET_BY_ID_SUCCESS';
// export const TOWERMASTER_GET_BY_ID_ERROR = 'modules/towerMaster/TOWERMASTER_GET_BY_ID_ERROR';

// export const TOWERMASTER_DELETE_REQUESTED = 'modules/towerMaster/TOWERMASTER_DELETE_REQUESTED';
// export const TOWERMASTER_DELETE_SUCCESS = 'modules/towerMaster/TOWERMASTER_DELETE_SUCCESS';
// export const TOWERMASTER_DELETE_ERROR = 'modules/towerMaster/TOWERMASTER_DELETE_ERROR';

// export const TOWERMASTER_SAVE_REQUESTED = 'modules/towerMaster/TOWERMASTER_SAVE_REQUESTED';
// export const TOWERMASTER_SAVE_SUCCESS = 'modules/towerMaster/TOWERMASTER_SAVE_SUCCESS';
// export const TOWERMASTER_SAVE_ERROR = 'modules/towerMaster/TOWERMASTER_SAVE_ERROR';
// //#endregion

// //#region Tower Allotment Master
// export const TOWERALLOTMENTMASTER_INIT = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_INIT';
// export const TOWERALLOTMENTMASTER_LIST_REQUESTED = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_LIST_REQUESTED';
// export const TOWERALLOTMENTMASTER_LIST_SUCCESS = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_LIST_SUCCESS';

// export const TOWERALLOTMENTMASTER_GET_BY_ID_REQUESTED = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_GET_BY_ID_REQUESTED';
// export const TOWERALLOTMENTMASTER_GET_BY_ID_SUCCESS = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_GET_BY_ID_SUCCESS';
// export const TOWERALLOTMENTMASTER_GET_BY_ID_ERROR = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_GET_BY_ID_ERROR';

// export const TOWERALLOTMENTMASTER_DELETE_REQUESTED = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_DELETE_REQUESTED';
// export const TOWERALLOTMENTMASTER_DELETE_SUCCESS = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_DELETE_SUCCESS';
// export const TOWERALLOTMENTMASTER_DELETE_ERROR = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_DELETE_ERROR';

// export const TOWERALLOTMENTMASTER_SAVE_REQUESTED = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_SAVE_REQUESTED';
// export const TOWERALLOTMENTMASTER_SAVE_SUCCESS = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_SAVE_SUCCESS';
// export const TOWERALLOTMENTMASTER_SAVE_ERROR = 'modules/towerAllotmentMaster/TOWERALLOTMENTMASTER_SAVE_ERROR';
// //#endregion

// //#region Tower Antennas Master
// export const TOWERANTENNASMASTER_INIT = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_INIT';
// export const TOWERANTENNASMASTER_LIST_REQUESTED = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_LIST_REQUESTED';
// export const TOWERANTENNASMASTER_LIST_SUCCESS = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_LIST_SUCCESS';

// export const TOWERANTENNASMASTER_GET_BY_ID_REQUESTED = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_GET_BY_ID_REQUESTED';
// export const TOWERANTENNASMASTER_GET_BY_ID_SUCCESS = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_GET_BY_ID_SUCCESS';
// export const TOWERANTENNASMASTER_GET_BY_ID_ERROR = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_GET_BY_ID_ERROR';

// export const TOWERANTENNASMASTER_DELETE_REQUESTED = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_DELETE_REQUESTED';
// export const TOWERANTENNASMASTER_DELETE_SUCCESS = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_DELETE_SUCCESS';
// export const TOWERANTENNASMASTER_DELETE_ERROR = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_DELETE_ERROR';

// export const TOWERANTENNASMASTER_SAVE_REQUESTED = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_SAVE_REQUESTED';
// export const TOWERANTENNASMASTER_SAVE_SUCCESS = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_SAVE_SUCCESS';
// export const TOWERANTENNASMASTER_SAVE_ERROR = 'modules/towerAntennasMaster/TOWERANTENNASMASTER_SAVE_ERROR';
// //#endregion

//#region Device Registration Master
export const DEVICEREGISTRATIONMASTER_INIT = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_INIT';
export const DEVICEREGISTRATIONMASTER_LIST_REQUESTED = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_LIST_REQUESTED';
export const DEVICEREGISTRATIONMASTER_LIST_SUCCESS = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_LIST_SUCCESS';

export const DEVICEREGISTRATIONMASTER_GET_BY_ID_REQUESTED = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_GET_BY_ID_REQUESTED';
export const DEVICEREGISTRATIONMASTER_GET_BY_ID_SUCCESS = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_GET_BY_ID_SUCCESS';
export const DEVICEREGISTRATIONMASTER_GET_BY_ID_ERROR = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_GET_BY_ID_ERROR';

export const DEVICEREGISTRATIONMASTER_DELETE_REQUESTED = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_DELETE_REQUESTED';
export const DEVICEREGISTRATIONMASTER_DELETE_SUCCESS = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_DELETE_SUCCESS';
export const DEVICEREGISTRATIONMASTER_DELETE_ERROR = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_DELETE_ERROR';

export const DEVICEREGISTRATIONMASTER_SAVE_REQUESTED = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_SAVE_REQUESTED';
export const DEVICEREGISTRATIONMASTER_SAVE_SUCCESS = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_SAVE_SUCCESS';
export const DEVICEREGISTRATIONMASTER_SAVE_ERROR = 'modules/deviceRegistrationMaster/DEVICEREGISTRATIONMASTER_SAVE_ERROR';
//#endregion

//#region Organisation Module Details

export const ORGANISATIONGROUPMODULEMASTER_INIT = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_INIT';
export const ORGANISATIONGROUPMODULEMASTER_LIST_REQUESTED = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_LIST_REQUESTED';
export const ORGANISATIONGROUPMODULEMASTER_LIST_SUCCESS = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_LIST_SUCCESS';

export const ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_REQUESTED = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_REQUESTED';
export const ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_SUCCESS = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_SUCCESS';
export const ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_ERROR = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_GET_BY_ID_ERROR';

export const ORGANISATIONGROUPMODULEMASTER_DELETE_REQUESTED = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_DELETE_REQUESTED';
export const ORGANISATIONGROUPMODULEMASTER_DELETE_SUCCESS = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_DELETE_SUCCESS';
export const ORGANISATIONGROUPMODULEMASTER_DELETE_ERROR = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_DELETE_ERROR';

export const ORGANISATIONGROUPMODULEMASTER_SAVE_REQUESTED = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_SAVE_REQUESTED';
export const ORGANISATIONGROUPMODULEMASTER_SAVE_SUCCESS = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_SAVE_SUCCESS';
export const ORGANISATIONGROUPMODULEMASTER_SAVE_ERROR = 'modules/organisationGroupModuleDetails/ORGANISATIONGROUPMODULEMASTER_SAVE_ERROR';


//#endregion