//#region Group Master
export const GROUPMASTER_INIT = 'modules/groupmaster/GROUPMASTER_INIT';
export const GROUPMASTER_LIST_REQUESTED = 'modules/groupmaster/GROUPMASTER_LIST_REQUESTED';
export const GROUPMASTER_LIST_SUCCESS = 'modules/groupmaster/GROUPMASTER_LIST_SUCCESS';

export const GROUPMASTER_GET_BY_ID_REQUESTED = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_REQUESTED';
export const GROUPMASTER_GET_BY_ID_SUCCESS = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_SUCCESS';
export const GROUPMASTER_GET_BY_ID_ERROR = 'modules/groupmaster/GROUPMASTER_GET_BY_ID_ERROR';

export const GROUPMASTER_DELETE_REQUESTED = 'modules/groupmaster/GROUPMASTER_DELETE_REQUESTED';
export const GROUPMASTER_DELETE_SUCCESS = 'modules/groupmaster/GROUPMASTER_DELETE_SUCCESS';
export const GROUPMASTER_DELETE_ERROR = 'modules/groupmaster/GROUPMASTER_DELETE_ERROR';

export const GROUPMASTER_SAVE_REQUESTED = 'modules/groupmaster/GROUPMASTER_SAVE_REQUESTED';
export const GROUPMASTER_SAVE_SUCCESS = 'modules/groupmaster/GROUPMASTER_SAVE_SUCCESS';
export const GROUPMASTER_SAVE_ERROR = 'modules/groupmaster/GROUPMASTER_SAVE_ERROR';
//#endregion

//#region Group Master
export const ORGRELATIONTYPEMASTER_INIT = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_INIT';
export const ORGRELATIONTYPEMASTER_LIST_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_LIST_REQUESTED';
export const ORGRELATIONTYPEMASTER_LIST_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_LIST_SUCCESS';

export const ORGRELATIONTYPEMASTER_GET_BY_ID_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_REQUESTED';
export const ORGRELATIONTYPEMASTER_GET_BY_ID_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_SUCCESS';
export const ORGRELATIONTYPEMASTER_GET_BY_ID_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_GET_BY_ID_ERROR';

export const ORGRELATIONTYPEMASTER_DELETE_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_REQUESTED';
export const ORGRELATIONTYPEMASTER_DELETE_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_SUCCESS';
export const ORGRELATIONTYPEMASTER_DELETE_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_DELETE_ERROR';

export const ORGRELATIONTYPEMASTER_SAVE_REQUESTED = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_REQUESTED';
export const ORGRELATIONTYPEMASTER_SAVE_SUCCESS = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_SUCCESS';
export const ORGRELATIONTYPEMASTER_SAVE_ERROR = 'modules/orgrelationtypemaster/ORGRELATIONTYPEMASTER_SAVE_ERROR';
//#endregion

//#region Module Master
export const MODULEMASTER_INIT = 'modules/modulemasetr/MODULEMASTER_INIT';
export const MODULEMASTER_LIST_REQUESTED = 'modules/modulemasetr/MODULEMASTER_LIST_REQUESTED';
export const MODULEMASTER_LIST_SUCCESS = 'modules/modulemasetr/MODULEMASTER_LIST_SUCCESS';

export const MODULEMASTER_GET_BY_ID_REQUESTED = 'modules/modulemasetr/MODULEMASTER_GET_BY_ID_REQUESTED';
export const MODULEMASTER_GET_BY_ID_SUCCESS = 'modules/modulemasetr/MODULEMASTER_GET_BY_ID_SUCCESS';
export const MODULEMASTER_GET_BY_GROUPID_SUCCESS = 'modules/modulemasetr/MODULEMASTER_GET_BY_GROUPID_SUCCESS';
export const MODULEMASTER_GET_BY_ID_ERROR = 'modules/modulemasetr/MODULEMASTER_GET_BY_ID_ERROR';

export const MODULEMASTER_DELETE_REQUESTED = 'modules/modulemasetr/MODULEMASTER_DELETE_REQUESTED';
export const MODULEMASTER_DELETE_SUCCESS = 'modules/modulemasetr/MODULEMASTER_DELETE_SUCCESS';
export const MODULEMASTER_DELETE_ERROR = 'modules/modulemasetr/MODULEMASTER_DELETE_ERROR';

export const MODULEMASTER_SAVE_REQUESTED = 'modules/modulemasetr/MODULEMASTER_SAVE_REQUESTED';
export const MODULEMASTER_SAVE_SUCCESS = 'modules/modulemasetr/MODULEMASTER_SAVE_SUCCESS';
export const MODULEMASTER_SAVE_ERROR = 'modules/modulemasetr/MODULEMASTER_SAVE_ERROR';
//#endregion

//#region Role Master
export const ROLEMASTER_INIT = 'modules/rolemaster/ROLEMASTER_INIT';
export const ROLEMASTER_LIST_REQUESTED = 'modules/rolemaster/ROLEMASTER_LIST_REQUESTED';
export const ROLEMASTER_LIST_SUCCESS = 'modules/rolemaster/ROLEMASTER_LIST_SUCCESS';

export const ROLEMASTER_GET_BY_ID_REQUESTED = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_REQUESTED';
export const ROLEMASTER_GET_BY_ID_SUCCESS = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_SUCCESS';
export const ROLEMASTER_GET_BY_MODULEID_SUCCESS = 'modules/rolemaster/ROLEMASTER_GET_BY_MODULEID_SUCCESS';
export const ROLEMASTER_GET_BY_ID_ERROR = 'modules/rolemaster/ROLEMASTER_GET_BY_ID_ERROR';

export const ROLEMASTER_DELETE_REQUESTED = 'modules/rolemaster/ROLEMASTER_DELETE_REQUESTED';
export const ROLEMASTER_DELETE_SUCCESS = 'modules/rolemaster/ROLEMASTER_DELETE_SUCCESS';
export const ROLEMASTER_DELETE_ERROR = 'modules/rolemaster/ROLEMASTER_DELETE_ERROR';

export const ROLEMASTER_SAVE_REQUESTED = 'modules/rolemaster/ROLEMASTER_SAVE_REQUESTED';
export const ROLEMASTER_SAVE_SUCCESS = 'modules/rolemaster/ROLEMASTER_SAVE_SUCCESS';
export const ROLEMASTER_SAVE_ERROR = 'modules/rolemaster/ROLEMASTER_SAVE_ERROR';
//#endregion



//#region Group Company Master
export const COMPANYMASTER_INIT = 'modules/companymaster/COMPANYMASTER_INIT';
export const COMPANYMASTER_LIST_REQUESTED = 'modules/companymaster/COMPANYMASTER_LIST_REQUESTED';
export const COMPANYMASTER_LIST_SUCCESS = 'modules/companymaster/COMPANYMASTER_LIST_SUCCESS';

export const COMPANYMASTER_GET_BY_ID_REQUESTED = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_REQUESTED';
export const COMPANYMASTER_GET_BY_ID_SUCCESS = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_SUCCESS';
export const COMPANYMASTER_GET_BY_GROUPID_SUCCESS = 'modules/companymaster/COMPANYMASTER_GET_BY_GROUPID_SUCCESS';
export const COMPANYMASTER_GET_BY_ID_ERROR = 'modules/companymaster/COMPANYMASTER_GET_BY_ID_ERROR';

export const COMPANYMASTER_DELETE_REQUESTED = 'modules/companymaster/COMPANYMASTER_DELETE_REQUESTED';
export const COMPANYMASTER_DELETE_SUCCESS = 'modules/companymaster/COMPANYMASTER_DELETE_SUCCESS';
export const COMPANYMASTER_DELETE_ERROR = 'modules/companymaster/COMPANYMASTER_DELETE_ERROR';

export const COMPANYMASTER_SAVE_REQUESTED = 'modules/companymaster/COMPANYMASTER_SAVE_REQUESTED';
export const COMPANYMASTER_SAVE_SUCCESS = 'modules/companymaster/COMPANYMASTER_SAVE_SUCCESS';
export const COMPANYMASTER_SAVE_ERROR = 'modules/companymaster/COMPANYMASTER_SAVE_ERROR';
//#endregion

//#region Group Company Master
export const PLANTMASTER_INIT = 'modules/plantmaster/PLANTMASTER_INIT';
export const PLANTMASTER_LIST_REQUESTED = 'modules/plantmaster/PLANTMASTER_LIST_REQUESTED';
export const PLANTMASTER_LIST_SUCCESS = 'modules/plantmaster/PLANTMASTER_LIST_SUCCESS';

export const PLANTMASTER_GET_BY_ID_REQUESTED = 'modules/plantmaster/PLANTMASTER_GET_BY_ID_REQUESTED';
export const PLANTMASTER_GET_BY_ID_SUCCESS = 'modules/plantmaster/PLANTMASTER_GET_BY_ID_SUCCESS';
export const PLANTMASTER_GET_BY_GROUPCOMPANYID_SUCCESS = 'modules/plantmaster/PLANTMASTER_GET_BY_GROUPCOMPANYID_SUCCESS';
export const PLANTMASTER_GET_BY_ID_ERROR = 'modules/plantmaster/PLANTMASTER_GET_BY_ID_ERROR';

export const PLANTMASTER_DELETE_REQUESTED = 'modules/plantmaster/PLANTMASTER_DELETE_REQUESTED';
export const PLANTMASTER_DELETE_SUCCESS = 'modules/plantmaster/PLANTMASTER_DELETE_SUCCESS';
export const PLANTMASTER_DELETE_ERROR = 'modules/plantmaster/PLANTMASTER_DELETE_ERROR';

export const PLANTMASTER_SAVE_REQUESTED = 'modules/plantmaster/PLANTMASTER_SAVE_REQUESTED';
export const PLANTMASTER_SAVE_SUCCESS = 'modules/plantmaster/PLANTMASTER_SAVE_SUCCESS';
export const PLANTMASTER_SAVE_ERROR = 'modules/plantmaster/PLANTMASTER_SAVE_ERROR';
//#endregion

//#region User Master
export const USER_INIT = 'modules/usermaster/USER_INIT';
export const USER_LIST_REQUESTED = 'modules/usermaster/USER_LIST_REQUESTED';
export const USER_LIST_SUCCESS = 'modules/usermaster/USER_LIST_SUCCESS';

export const USER_GET_BY_ID_REQUESTED = 'modules/usermaster/USER_GET_BY_ID_REQUESTED';
export const USER_GET_BY_ID_SUCCESS = 'modules/usermaster/USER_GET_BY_ID_SUCCESS';
export const USER_GET_BY_PLANTID_SUCCESS = 'modules/usermaster/USER_GET_BY_PLANTID_SUCCESS';
export const USER_GET_BY_PLANTDEPARTMENTID_SUCCESS = 'modules/usermaster/USER_GET_BY_PLANTDEPARTMENTID_SUCCESS';
export const USER_GET_BY_ID_ERROR = 'modules/usermaster/USER_GET_BY_ID_ERROR';

export const USER_DELETE_REQUESTED = 'modules/usermaster/USER_DELETE_REQUESTED';
export const USER_DELETE_SUCCESS = 'modules/usermaster/USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'modules/usermaster/USER_DELETE_ERROR';

export const USER_SAVE_REQUESTED = 'modules/usermaster/USER_SAVE_REQUESTED';
export const USER_SAVE_SUCCESS = 'modules/usermaster/USER_SAVE_SUCCESS';
export const USER_SAVE_ERROR = 'modules/usermaster/USER_SAVE_ERROR';
export const USER_GET_BY_GROUPID_SUCCESS = 'modules/usermaster/USER_GET_BY_GROUPID_SUCCESS';
//#endregion

//#region Year Master
export const YEARMASTER_INIT = 'modules/yearmaster/YEARMASTER_INIT';
export const YEARMASTER_LIST_REQUESTED = 'modules/yearmaster/YEARMASTER_LIST_REQUESTED';
export const YEARMASTER_LIST_SUCCESS = 'modules/yearmaster/YEARMASTER_LIST_SUCCESS';

export const YEARMASTER_GET_BY_ID_REQUESTED = 'modules/yearmaster/YEARMASTER_GET_BY_ID_REQUESTED';
export const YEARMASTER_GET_BY_ID_SUCCESS = 'modules/yearmaster/YEARMASTER_GET_BY_ID_SUCCESS';
export const YEARMASTER_GET_BY_ID_ERROR = 'modules/yearmaster/YEARMASTER_GET_BY_ID_ERROR';

export const YEARMASTER_DELETE_REQUESTED = 'modules/yearmaster/YEARMASTER_DELETE_REQUESTED';
export const YEARMASTER_DELETE_SUCCESS = 'modules/yearmaster/YEARMASTER_DELETE_SUCCESS';
export const YEARMASTER_DELETE_ERROR = 'modules/yearmaster/YEARMASTER_DELETE_ERROR';

export const YEARMASTER_SAVE_REQUESTED = 'modules/yearmaster/YEARMASTER_SAVE_REQUESTED';
export const YEARMASTER_SAVE_SUCCESS = 'modules/yearmaster/YEARMASTER_SAVE_SUCCESS';
export const YEARMASTER_SAVE_ERROR = 'modules/yearmaster/YEARMASTER_SAVE_ERROR';
//#endregion

//#region Notification  Details
export const NOTIFICATIONMASTERDETAILS_INIT = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_INIT';
export const NOTIFICATIONMASTERDETAILS_LIST_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_LIST_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_LIST_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_LIST_SUCCESS';

export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_GET_BY_ID_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_GET_BY_ID_ERROR';

export const NOTIFICATIONMASTERDETAILS_DELETE_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_DELETE_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_DELETE_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_DELETE_ERROR';

export const NOTIFICATIONMASTERDETAILS_SAVE_REQUESTED = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_REQUESTED';
export const NOTIFICATIONMASTERDETAILS_SAVE_SUCCESS = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_SUCCESS';
export const NOTIFICATIONMASTERDETAILS_SAVE_ERROR = 'modules/notificationdetails/NOTIFICATIONMASTERDETAILS_SAVE_ERROR';
//#endregion

//#region ESCALATION MATRIX  Details
export const ESCALATIONMATRIXDETAILS_INIT = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_INIT';
export const ESCALATIONMATRIXDETAILS_LIST_REQUESTED = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_LIST_REQUESTED';
export const ESCALATIONMATRIXDETAILS_LIST_SUCCESS = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_LIST_SUCCESS';

export const ESCALATIONMATRIXDETAILS_GET_BY_ID_REQUESTED = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_GET_BY_ID_REQUESTED';
export const ESCALATIONMATRIXDETAILS_GET_BY_ID_SUCCESS = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_GET_BY_ID_SUCCESS';
export const ESCALATIONMATRIXDETAILS_GET_BY_ID_ERROR = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_GET_BY_ID_ERROR';

export const ESCALATIONMATRIXDETAILS_DELETE_REQUESTED = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_DELETE_REQUESTED';
export const ESCALATIONMATRIXDETAILS_DELETE_SUCCESS = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_DELETE_SUCCESS';
export const ESCALATIONMATRIXDETAILS_DELETE_ERROR = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_DELETE_ERROR';

export const ESCALATIONMATRIXDETAILS_SAVE_REQUESTED = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_SAVE_REQUESTED';
export const ESCALATIONMATRIXDETAILS_SAVE_SUCCESS = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_SAVE_SUCCESS';
export const ESCALATIONMATRIXDETAILS_SAVE_ERROR = 'modules/escalationmatrix/ESCALATIONMATRIXDETAILS_SAVE_ERROR';
//#endregion


//#region ESCALATION Duration  Details
export const ESCALATIONDURATIONDETAILS_INIT = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_INIT';
export const ESCALATIONDURATIONDETAILS_LIST_REQUESTED = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_LIST_REQUESTED';
export const ESCALATIONDURATIONDETAILS_LIST_SUCCESS = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_LIST_SUCCESS';

export const ESCALATIONDURATIONDETAILS_GET_BY_ID_REQUESTED = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_GET_BY_ID_REQUESTED';
export const ESCALATIONDURATIONDETAILS_GET_BY_ID_SUCCESS = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_GET_BY_ID_SUCCESS';
export const ESCALATIONDURATIONDETAILS_GET_BY_ID_ERROR = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_GET_BY_ID_ERROR';

export const ESCALATIONDURATIONDETAILS_DELETE_REQUESTED = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_DELETE_REQUESTED';
export const ESCALATIONDURATIONDETAILS_DELETE_SUCCESS = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_DELETE_SUCCESS';
export const ESCALATIONDURATIONDETAILS_DELETE_ERROR = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_DELETE_ERROR';

export const ESCALATIONDURATIONDETAILS_SAVE_REQUESTED = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_SAVE_REQUESTED';
export const ESCALATIONDURATIONDETAILS_SAVE_SUCCESS = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_SAVE_SUCCESS';
export const ESCALATIONDURATIONDETAILS_SAVE_ERROR = 'modules/escalationduration/ESCALATIONDURATIONDETAILS_SAVE_ERROR';
//#endregion



//#region ESCALATION Duration  Details
export const SUPPORTINGDOCUMENTMASTER_INIT = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_INIT';
export const SUPPORTINGDOCUMENTMASTER_LIST_REQUESTED = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_LIST_REQUESTED';
export const SUPPORTINGDOCUMENTMASTER_LIST_SUCCESS = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_LIST_SUCCESS';

export const SUPPORTINGDOCUMENTMASTER_GET_BY_ID_REQUESTED = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_GET_BY_ID_REQUESTED';
export const SUPPORTINGDOCUMENTMASTER_GET_BY_ID_SUCCESS = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_GET_BY_ID_SUCCESS';
export const SUPPORTINGDOCUMENTMASTER_GET_BY_ID_ERROR = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_GET_BY_ID_ERROR';

export const SUPPORTINGDOCUMENTMASTER_DELETE_REQUESTED = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_DELETE_REQUESTED';
export const SUPPORTINGDOCUMENTMASTER_DELETE_SUCCESS = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_DELETE_SUCCESS';
export const SUPPORTINGDOCUMENTMASTER_DELETE_ERROR = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_DELETE_ERROR';

export const SUPPORTINGDOCUMENTMASTER_SAVE_REQUESTED = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_SAVE_REQUESTED';
export const SUPPORTINGDOCUMENTMASTER_SAVE_SUCCESS = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_SAVE_SUCCESS';
export const SUPPORTINGDOCUMENTMASTER_SAVE_ERROR = 'modules/supportingdocumentmaster/SUPPORTINGDOCUMENTMASTER_SAVE_ERROR';
//#endregion

//#region Due Dyas Master
export const DUEDAYSMASTER_INIT = 'modules/duedaysmaster/DUEDAYSMASTER_INIT';
export const DUEDAYSMASTER_LIST_REQUESTED = 'modules/duedaysmaster/DUEDAYSMASTER_LIST_REQUESTED';
export const DUEDAYSMASTER_LIST_SUCCESS = 'modules/duedaysmaster/DUEDAYSMASTER_LIST_SUCCESS';

export const DUEDAYSMASTER_GET_BY_ID_REQUESTED = 'modules/duedaysmaster/DUEDAYSMASTER_GET_BY_ID_REQUESTED';
export const DUEDAYSMASTER_GET_BY_ID_SUCCESS = 'modules/duedaysmaster/DUEDAYSMASTER_GET_BY_ID_SUCCESS';
export const DUEDAYSMASTER_GET_BY_ID_ERROR = 'modules/duedaysmaster/DUEDAYSMASTER_GET_BY_ID_ERROR';

export const DUEDAYSMASTER_DELETE_REQUESTED = 'modules/duedaysmaster/DUEDAYSMASTER_DELETE_REQUESTED';
export const DUEDAYSMASTER_DELETE_SUCCESS = 'modules/duedaysmaster/DUEDAYSMASTER_DELETE_SUCCESS';
export const DUEDAYSMASTER_DELETE_ERROR = 'modules/duedaysmaster/DUEDAYSMASTER_DELETE_ERROR';

export const DUEDAYSMASTER_SAVE_REQUESTED = 'modules/duedaysmaster/DUEDAYSMASTER_SAVE_REQUESTED';
export const DUEDAYSMASTER_SAVE_SUCCESS = 'modules/duedaysmaster/DUEDAYSMASTER_SAVE_SUCCESS';
export const DUEDAYSMASTER_SAVE_ERROR = 'modules/duedaysmaster/DUEDAYSMASTER_SAVE_ERROR';
//#endregion

//#region Status Master
export const STATUSMASTER_INIT = 'modules/statusmaster/STATUSMASTER_INIT';
export const STATUSMASTER_LIST_REQUESTED = 'modules/statusmaster/STATUSMASTER_LIST_REQUESTED';
export const STATUSMASTER_LIST_SUCCESS = 'modules/statusmaster/STATUSMASTER_LIST_SUCCESS';
export const STATUSMASTER_LIST_ERROR = 'modules/statusmaster/STATUSMASTER_LIST_ERROR';

export const STATUSMASTER_GET_BY_ID_REQUESTED = 'modules/statusmaster/STATUSMASTER_GET_BY_ID_REQUESTED';
export const STATUSMASTER_GET_BY_ID_SUCCESS = 'modules/statusmaster/STATUSMASTER_GET_BY_ID_SUCCESS';
export const STATUSMASTER_GET_BY_ID_ERROR = 'modules/statusmaster/STATUSMASTER_GET_BY_ID_ERROR';

export const STATUSMASTER_DELETE_REQUESTED = 'modules/statusmaster/STATUSMASTER_DELETE_REQUESTED';
export const STATUSMASTER_DELETE_SUCCESS = 'modules/statusmaster/STATUSMASTER_DELETE_SUCCESS';
export const STATUSMASTER_DELETE_ERROR = 'modules/statusmaster/STATUSMASTER_DELETE_ERROR';

export const STATUSMASTER_SAVE_REQUESTED = 'modules/statusmaster/STATUSMASTER_SAVE_REQUESTED';
export const STATUSMASTER_SAVE_SUCCESS = 'modules/statusmaster/STATUSMASTER_SAVE_SUCCESS';
export const STATUSMASTER_SAVE_ERROR = 'modules/statusmaster/STATUSMASTER_SAVE_ERROR';
//#endregion 

//#region Year Type Master
export const YEARTYPEMASTER_INIT = 'modules/yearTypeMaster/YEARTYPEMASTER_INIT';
export const YEARTYPEMASTER_LIST_REQUESTED = 'modules/yearTypeMaster/YEARTYPEMASTER_LIST_REQUESTED';
export const YEARTYPEMASTER_LIST_SUCCESS = 'modules/yearTypeMaster/YEARTYPEMASTER_LIST_SUCCESS';
export const YEARTYPEMASTER_LIST_ERROR = 'modules/yearTypeMaster/YEARTYPEMASTER_LIST_ERROR';

export const YEARTYPEMASTER_GET_BY_ID_REQUESTED = 'modules/yearTypeMaster/YEARTYPEMASTER_GET_BY_ID_REQUESTED';
export const YEARTYPEMASTER_GET_BY_ID_SUCCESS = 'modules/yearTypeMaster/YEARTYPEMASTER_GET_BY_ID_SUCCESS';
export const YEARTYPEMASTER_GET_BY_ID_ERROR = 'modules/yearTypeMaster/YEARTYPEMASTER_GET_BY_ID_ERROR';

export const YEARTYPEMASTER_DELETE_REQUESTED = 'modules/yearTypeMaster/YEARTYPEMASTER_DELETE_REQUESTED';
export const YEARTYPEMASTER_DELETE_SUCCESS = 'modules/yearTypeMaster/YEARTYPEMASTER_DELETE_SUCCESS';
export const YEARTYPEMASTER_DELETE_ERROR = 'modules/yearTypeMaster/YEARTYPEMASTER_DELETE_ERROR';

export const YEARTYPEMASTER_SAVE_REQUESTED = 'modules/yearTypeMaster/YEARTYPEMASTER_SAVE_REQUESTED';
export const YEARTYPEMASTER_SAVE_SUCCESS = 'modules/yearTypeMaster/YEARTYPEMASTER_SAVE_SUCCESS';
export const YEARTYPEMASTER_SAVE_ERROR = 'modules/yearTypeMaster/YEARTYPEMASTER_SAVE_ERROR';
//#endregion 

//#region Section Master
export const SECTIONMASTER_INIT = 'modules/sectionmaster/SECTIONMASTER_INIT';
export const SECTIONMASTER_LIST_REQUESTED = 'modules/sectionmaster/SECTIONMASTER_LIST_REQUESTED';
export const SECTIONMASTER_LIST_SUCCESS = 'modules/sectionmaster/SECTIONMASTER_LIST_SUCCESS';

export const SECTIONMASTER_GET_BY_ID_REQUESTED = 'modules/sectionmaster/SECTIONMASTER_GET_BY_ID_REQUESTED';
export const SECTIONMASTER_GET_BY_ID_SUCCESS = 'modules/sectionmaster/SECTIONMASTER_GET_BY_ID_SUCCESS';
export const SECTIONMASTER_GET_BY_ID_ERROR = 'modules/sectionmaster/SECTIONMASTER_GET_BY_ID_ERROR';

export const SECTIONMASTER_DELETE_REQUESTED = 'modules/sectionmaster/SECTIONMASTER_DELETE_REQUESTED';
export const SECTIONMASTER_DELETE_SUCCESS = 'modules/sectionmaster/SECTIONMASTER_DELETE_SUCCESS';
export const SECTIONMASTER_DELETE_ERROR = 'modules/sectionmaster/SECTIONMASTER_DELETE_ERROR';

export const SECTIONMASTER_SAVE_REQUESTED = 'modules/sectionmaster/SECTIONMASTER_SAVE_REQUESTED';
export const SECTIONMASTER_SAVE_SUCCESS = 'modules/sectionmaster/SECTIONMASTER_SAVE_SUCCESS';
export const SECTIONMASTER_SAVE_ERROR = 'modules/sectionmaster/SECTIONMASTER_SAVE_ERROR';
//#endregion

//#region Sub Section Master
export const SUBSECTIONMASTER_INIT = 'modules/subSectionmaster/SUBSECTIONMASTER_INIT';
export const SUBSECTIONMASTER_LIST_REQUESTED = 'modules/subSectionmaster/SUBSECTIONMASTER_LIST_REQUESTED';
export const SUBSECTIONMASTER_LIST_SUCCESS = 'modules/subSectionmaster/SUBSECTIONMASTER_LIST_SUCCESS';

export const SUBSECTIONMASTER_GET_BY_ID_REQUESTED = 'modules/subSectionmaster/SUBSECTIONMASTER_GET_BY_ID_REQUESTED';
export const SUBSECTIONMASTER_GET_BY_ID_SUCCESS = 'modules/subSectionmaster/SUBSECTIONMASTER_GET_BY_ID_SUCCESS';
export const SUBSECTIONMASTER_GET_BY_ID_ERROR = 'modules/subSectionmaster/SUBSECTIONMASTER_GET_BY_ID_ERROR';

export const SUBSECTIONMASTER_DELETE_REQUESTED = 'modules/subSectionmaster/SUBSECTIONMASTER_DELETE_REQUESTED';
export const SUBSECTIONMASTER_DELETE_SUCCESS = 'modules/subSectionmaster/SUBSECTIONMASTER_DELETE_SUCCESS';
export const SUBSECTIONMASTER_DELETE_ERROR = 'modules/subSectionmaster/SUBSECTIONMASTER_DELETE_ERROR';

export const SUBSECTIONMASTER_SAVE_REQUESTED = 'modules/subSectionmaster/SUBSECTIONMASTER_SAVE_REQUESTED';
export const SUBSECTIONMASTER_SAVE_SUCCESS = 'modules/subSectionmaster/SUBSECTIONMASTER_SAVE_SUCCESS';
export const SUBSECTIONMASTER_SAVE_ERROR = 'modules/subSectionmaster/SUBSECTIONMASTER_SAVE_ERROR';
//#endregion

//#region Scoring Rule Master
export const SCORINGRULEMASTER_INIT = 'modules/scoringRuleMaster/SCORINGRULEMASTER_INIT';
export const SCORINGRULEMASTER_LIST_REQUESTED = 'modules/scoringRuleMaster/SCORINGRULEMASTER_LIST_REQUESTED';
export const SCORINGRULEMASTER_LIST_SUCCESS = 'modules/scoringRuleMaster/SCORINGRULEMASTER_LIST_SUCCESS';

export const SCORINGRULEMASTER_GET_BY_ID_REQUESTED = 'modules/scoringRuleMaster/SCORINGRULEMASTER_GET_BY_ID_REQUESTED';
export const SCORINGRULEMASTER_GET_BY_ID_SUCCESS = 'modules/scoringRuleMaster/SCORINGRULEMASTER_GET_BY_ID_SUCCESS';
export const SCORINGRULEMASTER_GET_BY_ID_ERROR = 'modules/scoringRuleMaster/SCORINGRULEMASTER_GET_BY_ID_ERROR';

export const SCORINGRULEMASTER_DELETE_REQUESTED = 'modules/scoringRuleMaster/SCORINGRULEMASTER_DELETE_REQUESTED';
export const SCORINGRULEMASTER_DELETE_SUCCESS = 'modules/scoringRuleMaster/SCORINGRULEMASTER_DELETE_SUCCESS';
export const SCORINGRULEMASTER_DELETE_ERROR = 'modules/scoringRuleMaster/SCORINGRULEMASTER_DELETE_ERROR';

export const SCORINGRULEMASTER_SAVE_REQUESTED = 'modules/scoringRuleMaster/SCORINGRULEMASTER_SAVE_REQUESTED';
export const SCORINGRULEMASTER_SAVE_SUCCESS = 'modules/scoringRuleMaster/SCORINGRULEMASTER_SAVE_SUCCESS';
export const SCORINGRULEMASTER_SAVE_ERROR = 'modules/scoringRuleMaster/SCORINGRULEMASTER_SAVE_ERROR';
//#endregion

//#region Audit Type
export const AUDITTYPEMASTER_INIT = 'modules/audittype/AUDITTYPEMASTER_INIT';
export const AUDITTYPEMASTER_LIST_REQUESTED = 'modules/audittype/AUDITTYPEMASTER_LIST_REQUESTED';
export const AUDITTYPEMASTER_LIST_SUCCESS = 'modules/audittype/AUDITTYPEMASTER_LIST_SUCCESS';
//#endregion

//#region Audit Flow
export const AUDITFLOWMASTER_INIT = 'modules/auditFlow/AUDITFLOWMASTER_INIT';
export const AUDITFLOWMASTER_LIST_REQUESTED = 'modules/auditFlow/AUDITFLOWMASTER_LIST_REQUESTED';
export const AUDITFLOWMASTER_LIST_SUCCESS = 'modules/auditFlow/AUDITFLOWMASTER_LIST_SUCCESS';
//#endregion

//#region Process Flow Master
export const PROCESSFLOWMASTER_INIT = 'modules/processFlowMaster/PROCESSFLOWMASTER_INIT';
export const PROCESSFLOWMASTER_LIST_REQUESTED = 'modules/processFlowMaster/PROCESSFLOWMASTER_LIST_REQUESTED';
export const PROCESSFLOWMASTER_LIST_SUCCESS = 'modules/processFlowMaster/PROCESSFLOWMASTER_LIST_SUCCESS';

export const PROCESSFLOWMASTER_GET_BY_ID_REQUESTED = 'modules/processFlowMaster/PROCESSFLOWMASTER_GET_BY_ID_REQUESTED';
export const PROCESSFLOWMASTER_GET_BY_ID_SUCCESS = 'modules/processFlowMaster/PROCESSFLOWMASTER_GET_BY_ID_SUCCESS';
export const PROCESSFLOWMASTER_GET_BY_ID_ERROR = 'modules/processFlowMaster/PROCESSFLOWMASTER_GET_BY_ID_ERROR';

export const PROCESSFLOWMASTER_DELETE_REQUESTED = 'modules/processFlowMaster/PROCESSFLOWMASTER_DELETE_REQUESTED';
export const PROCESSFLOWMASTER_DELETE_SUCCESS = 'modules/processFlowMaster/PROCESSFLOWMASTER_DELETE_SUCCESS';
export const PROCESSFLOWMASTER_DELETE_ERROR = 'modules/processFlowMaster/PROCESSFLOWMASTER_DELETE_ERROR';

export const PROCESSFLOWMASTER_SAVE_REQUESTED = 'modules/processFlowMaster/PROCESSFLOWMASTER_SAVE_REQUESTED';
export const PROCESSFLOWMASTER_SAVE_SUCCESS = 'modules/processFlowMaster/PROCESSFLOWMASTER_SAVE_SUCCESS';
export const PROCESSFLOWMASTER_SAVE_ERROR = 'modules/processFlowMaster/PROCESSFLOWMASTER_SAVE_ERROR';
//#endregion

//#region Audit Observation Master
export const AUDITOBSERVATIONMASTER_INIT = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_INIT';
export const AUDITOBSERVATIONMASTER_LIST_REQUESTED = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_LIST_REQUESTED';
export const AUDITOBSERVATIONMASTER_LIST_SUCCESS = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_LIST_SUCCESS';

export const AUDITOBSERVATIONMASTER_GET_BY_ID_REQUESTED = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_GET_BY_ID_REQUESTED';
export const AUDITOBSERVATIONMASTER_GET_BY_ID_SUCCESS = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_GET_BY_ID_SUCCESS';
export const AUDITOBSERVATIONMASTER_GET_BY_ID_ERROR = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_GET_BY_ID_ERROR';

export const AUDITOBSERVATIONMASTER_DELETE_REQUESTED = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_DELETE_REQUESTED';
export const AUDITOBSERVATIONMASTER_DELETE_SUCCESS = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_DELETE_SUCCESS';
export const AUDITOBSERVATIONMASTER_DELETE_ERROR = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_DELETE_ERROR';

export const AUDITOBSERVATIONMASTER_SAVE_REQUESTED = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_SAVE_REQUESTED';
export const AUDITOBSERVATIONMASTER_SAVE_SUCCESS = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_SAVE_SUCCESS';
export const AUDITOBSERVATIONMASTER_SAVE_ERROR = 'modules/auditobservationmaster/AUDITOBSERVATIONMASTER_SAVE_ERROR';
//#endregion


//#region criticality Master
export const CRITICALITYMASTER_INIT = 'modules/criticalitymaster/CRITICALITYMASTER_INIT';
export const CRITICALITYMASTER_LIST_REQUESTED = 'modules/criticalitymaster/CRITICALITYMASTER_LIST_REQUESTED';
export const CRITICALITYMASTER_LIST_SUCCESS = 'modules/criticalitymaster/CRITICALITYMASTER_LIST_SUCCESS';

export const CRITICALITYMASTER_GET_BY_ID_REQUESTED = 'modules/criticalitymaster/CRITICALITYMASTER_GET_BY_ID_REQUESTED';
export const CRITICALITYMASTER_GET_BY_ID_SUCCESS = 'modules/criticalitymaster/CRITICALITYMASTER_GET_BY_ID_SUCCESS';
export const CRITICALITYMASTER_GET_BY_ID_ERROR = 'modules/criticalitymaster/CRITICALITYMASTER_GET_BY_ID_ERROR';

export const CRITICALITYMASTER_DELETE_REQUESTED = 'modules/criticalitymaster/CRITICALITYMASTER_DELETE_REQUESTED';
export const CRITICALITYMASTER_DELETE_SUCCESS = 'modules/criticalitymaster/CRITICALITYMASTER_DELETE_SUCCESS';
export const CRITICALITYMASTER_DELETE_ERROR = 'modules/criticalitymaster/CRITICALITYMASTER_DELETE_ERROR';

export const CRITICALITYMASTER_SAVE_REQUESTED = 'modules/criticalitymaster/CRITICALITYMASTER_SAVE_REQUESTED';
export const CRITICALITYMASTER_SAVE_SUCCESS = 'modules/criticalitymaster/CRITICALITYMASTER_SAVE_SUCCESS';
export const CRITICALITYMASTER_SAVE_ERROR = 'modules/criticalitymaster/CRITICALITYMASTER_SAVE_ERROR';
//#endregion



//#region Audit Type Auditor Relation Master
export const AUDITTYPEAUDITORRELATIONMASTER_INIT = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_INIT';
export const AUDITTYPEAUDITORRELATIONMASTER_LIST_REQUESTED = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_LIST_REQUESTED';
export const AUDITTYPEAUDITORRELATIONMASTER_LIST_SUCCESS = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_LIST_SUCCESS';

export const AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_REQUESTED = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_REQUESTED';
export const AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_SUCCESS = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_SUCCESS';
export const AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_ERROR = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_GET_BY_ID_ERROR';

export const AUDITTYPEAUDITORRELATIONMASTER_DELETE_REQUESTED = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_DELETE_REQUESTED';
export const AUDITTYPEAUDITORRELATIONMASTER_DELETE_SUCCESS = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_DELETE_SUCCESS';
export const AUDITTYPEAUDITORRELATIONMASTER_DELETE_ERROR = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_DELETE_ERROR';

export const AUDITTYPEAUDITORRELATIONMASTER_SAVE_REQUESTED = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_SAVE_REQUESTED';
export const AUDITTYPEAUDITORRELATIONMASTER_SAVE_SUCCESS = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_SAVE_SUCCESS';
export const AUDITTYPEAUDITORRELATIONMASTER_SAVE_ERROR = 'modules/audittypeauditorrelationmaster/AUDITTYPEAUDITORRELATIONMASTER_SAVE_ERROR';
//#endregion

//#region Scope Master
export const SCOPEMASTER_INIT = 'modules/scopemaster/SCOPEMASTER_INIT';
export const SCOPEMASTER_LIST_REQUESTED = 'modules/scopemaster/SCOPEMASTER_LIST_REQUESTED';
export const SCOPEMASTER_LIST_SUCCESS = 'modules/scopemaster/SCOPEMASTER_LIST_SUCCESS';

export const SCOPEMASTER_GET_BY_ID_REQUESTED = 'modules/scopemaster/SCOPEMASTER_GET_BY_ID_REQUESTED';
export const SCOPEMASTER_GET_BY_ID_SUCCESS = 'modules/scopemaster/SCOPEMASTER_GET_BY_ID_SUCCESS';
export const SCOPEMASTER_GET_BY_ID_ERROR = 'modules/scopemaster/SCOPEMASTER_GET_BY_ID_ERROR';

export const SCOPEMASTER_DELETE_REQUESTED = 'modules/scopemaster/SCOPEMASTER_DELETE_REQUESTED';
export const SCOPEMASTER_DELETE_SUCCESS = 'modules/scopemaster/SCOPEMASTER_DELETE_SUCCESS';
export const SCOPEMASTER_DELETE_ERROR = 'modules/scopemaster/SCOPEMASTER_DELETE_ERROR';

export const SCOPEMASTER_SAVE_REQUESTED = 'modules/scopemaster/SCOPEMASTER_SAVE_REQUESTED';
export const SCOPEMASTER_SAVE_SUCCESS = 'modules/scopemaster/SCOPEMASTER_SAVE_SUCCESS';
export const SCOPEMASTER_SAVE_ERROR = 'modules/scopemaster/SCOPEMASTER_SAVE_ERROR';
//#endregion

//#region Process Flow Master
export const PROCESSFLOWRESPONSIBILITYMASTER_INIT = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_INIT';
export const PROCESSFLOWRESPONSIBILITYMASTER_LIST_REQUESTED = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_LIST_REQUESTED';
export const PROCESSFLOWRESPONSIBILITYMASTER_LIST_SUCCESS = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_LIST_SUCCESS';

export const PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_REQUESTED = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_REQUESTED';
export const PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_SUCCESS = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_SUCCESS';
export const PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_ERROR = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_GET_BY_ID_ERROR';

export const PROCESSFLOWRESPONSIBILITYMASTER_DELETE_REQUESTED = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_DELETE_REQUESTED';
export const PROCESSFLOWRESPONSIBILITYMASTER_DELETE_SUCCESS = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_DELETE_SUCCESS';
export const PROCESSFLOWRESPONSIBILITYMASTER_DELETE_ERROR = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_DELETE_ERROR';

export const PROCESSFLOWRESPONSIBILITYMASTER_SAVE_REQUESTED = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_SAVE_REQUESTED';
export const PROCESSFLOWRESPONSIBILITYMASTER_SAVE_SUCCESS = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_SAVE_SUCCESS';
export const PROCESSFLOWRESPONSIBILITYMASTER_SAVE_ERROR = 'modules/processFlowResponsibilityMaster/PROCESSFLOWRESPONSIBILITYMASTER_SAVE_ERROR';
//#endregion