export const MASTERCATEGORY_INIT = 'modules/mastercategory/MASTERCATEGORY_INIT';
export const MASTERCATEGORY_LIST_REQUESTED = 'modules/mastercategory/MASTERCATEGORY_LIST_REQUESTED';
export const MASTERCATEGORY_LIST_SUCCESS = 'modules/mastercategory/MASTERCATEGORY_LIST_SUCCESS';

export const MASTERCATEGORY_GET_BY_ID_REQUESTED = 'modules/mastercategory/MASTERCATEGORY_GET_BY_ID_REQUESTED';
export const MASTERCATEGORY_GET_BY_ID_SUCCESS = 'modules/mastercategory/MASTERCATEGORY_GET_BY_ID_SUCCESS';
//export const MASTERCATEGORY_GET_BY_CODE_SUCCESS = 'modules/mastercategory/MASTERCATEGORY_GET_BY_CODE_SUCCESS';
export const MASTERCATEGORY_GET_BY_ID_ERROR = 'modules/mastercategory/MASTERCATEGORY_GET_BY_ID_ERROR';

export const MASTERCATEGORY_DELETE_REQUESTED = 'modules/mastercategory/MASTERCATEGORY_DELETE_REQUESTED';
export const MASTERCATEGORY_DELETE_SUCCESS = 'modules/mastercategory/MASTERCATEGORY_DELETE_SUCCESS';
export const MASTERCATEGORY_DELETE_ERROR = 'modules/mastercategory/MASTERCATEGORY_DELETE_ERROR';

export const MASTERCATEGORY_SAVE_REQUESTED = 'modules/mastercategory/MASTERCATEGORY_SAVE_REQUESTED';
export const MASTERCATEGORY_SAVE_SUCCESS = 'modules/mastercategory/MASTERCATEGORY_SAVE_SUCCESS';
export const MASTERCATEGORY_SAVE_ERROR = 'modules/mastercategory/MASTERCATEGORY_SAVE_ERROR';