//#region  Pending Task Dahboard 
export const PENDINGTASKDASHBOARD_INIT = 'modules/pendingtaskdashboard/PENDINGTASKDASHBOARD_INIT';
export const PENDINGTASKDASHBOARD_LIST_REQUESTED = 'modules/pendingtaskdashboard/PENDINGTASKDASHBOARD_LIST_REQUESTED';
export const PENDINGTASKDASHBOARD_LIST_SUCCESS = 'modules/pendingtaskdashboard/PENDINGTASKDASHBOARD_LIST_SUCCESS';

//#endregion

//#region  Audit Observation Master For Execution
export const AUDITOBSERVATION_INIT = 'modules/observation/AUDITOBSERVATION_INIT';
export const AUDITOBSERVATION_LIST_REQUESTED = 'modules/observation/AUDITOBSERVATION_LIST_REQUESTED';
export const AUDITOBSERVATION_LIST_SUCCESS = 'modules/observation/AUDITOBSERVATION_LIST_SUCCESS';
//#endregion

//#region Self Audit Planning 
export const SELFAUDITPLANDETAILS_INIT = 'modules/selfauditplan/SELFAUDITPLANDETAILS_INIT';
export const SELFAUDITPLANDETAILS_LIST_REQUESTED = 'modules/selfauditplan/SELFAUDITPLANDETAILS_LIST_REQUESTED';
export const SELFAUDITPLANDETAILS_LIST_SUCCESS = 'modules/selfauditplan/SELFAUDITPLANDETAILS_LIST_SUCCESS';

export const SELFAUDITPLANDETAILS_GET_BY_ID_REQUESTED = 'modules/selfauditplan/SELFAUDITPLANDETAILS_GET_BY_ID_REQUESTED';
export const SELFAUDITPLANDETAILS_GET_BY_ID_SUCCESS = 'modules/selfauditplan/SELFAUDITPLANDETAILS_GET_BY_ID_SUCCESS';
export const SELFAUDITPLANDETAILS_GET_BY_ID_ERROR = 'modules/selfauditplan/SELFAUDITPLANDETAILS_GET_BY_ID_ERROR';

export const SELFAUDITPLANDETAILS_DELETE_REQUESTED = 'modules/selfauditplan/SELFAUDITPLANDETAILS_DELETE_REQUESTED';
export const SELFAUDITPLANDETAILS_DELETE_SUCCESS = 'modules/selfauditplan/SELFAUDITPLANDETAILS_DELETE_SUCCESS';
export const SELFAUDITPLANDETAILS_DELETE_ERROR = 'modules/selfauditplan/SELFAUDITPLANDETAILS_DELETE_ERROR';

export const SELFAUDITPLANDETAILS_SAVE_REQUESTED = 'modules/selfauditplan/SELFAUDITPLANDETAILS_SAVE_REQUESTED';
export const SELFAUDITPLANDETAILS_SAVE_SUCCESS = 'modules/selfauditplan/SELFAUDITPLANDETAILS_SAVE_SUCCESS';
export const SELFAUDITPLANDETAILS_SAVE_ERROR = 'modules/selfauditplan/SELFAUDITPLANDETAILS_SAVE_ERROR';
//#endregion

//#region Supporting Document  
export const SUPPORTINGDOC_INIT = 'modules/supportingdocument/SUPPORTINGDOC_INIT';
export const SUPPORTINGDOC_LIST_REQUESTED = 'modules/supportingdocument/SUPPORTINGDOC_LIST_REQUESTED';
export const SUPPORTINGDOC_LIST_SUCCESS = 'modules/supportingdocument/SUPPORTINGDOC_LIST_SUCCESS';

export const SUPPORTINGDOC_GET_BY_ID_REQUESTED = 'modules/supportingdocument/SUPPORTINGDOC_GET_BY_ID_REQUESTED';
export const SUPPORTINGDOC_GET_BY_ID_SUCCESS = 'modules/supportingdocument/SUPPORTINGDOC_GET_BY_ID_SUCCESS';
export const SUPPORTINGDOC_GET_BY_ID_ERROR = 'modules/supportingdocument/SUPPORTINGDOC_GET_BY_ID_ERROR';

export const SUPPORTINGDOC_DELETE_REQUESTED = 'modules/supportingdocument/SUPPORTINGDOC_DELETE_REQUESTED';
export const SUPPORTINGDOC_DELETE_SUCCESS = 'modules/supportingdocument/SUPPORTINGDOC_DELETE_SUCCESS';
export const SUPPORTINGDOC_DELETE_ERROR = 'modules/supportingdocument/SUPPORTINGDOC_DELETE_ERROR';

export const SUPPORTINGDOC_SAVE_REQUESTED = 'modules/supportingdocument/SUPPORTINGDOC_SAVE_REQUESTED';
export const SUPPORTINGDOC_SAVE_SUCCESS = 'modules/supportingdocument/SUPPORTINGDOC_SAVE_SUCCESS';
export const SUPPORTINGDOC_SAVE_ERROR = 'modules/supportingdocument/SUPPORTINGDOC_SAVE_ERROR';
//#endregion

//#region Self Audit Details Process Flow Wise
export const SELFAUDITDETAILS_RESPONSIBILITYWISE_INIT = 'modules/sa_teamassignmentandexecution/SELFAUDITDETAILS_RESPONSIBILITYWISE_INIT';
export const SELFAUDITDETAILS_RESPONSIBILITYWISE_LIST_REQUESTED = 'modules/sa_teamassignmentandexecution/SELFAUDITDETAILS_RESPONSIBILITYWISE_LIST_REQUESTED';
export const SELFAUDITDETAILS_RESPONSIBILITYWISE_LIST_SUCCESS = 'modules/sa_teamassignmentandexecution/SELFAUDITDETAILS_RESPONSIBILITYWISE_LIST_SUCCESS';

//#endregion

//#region  Self Audit Team Assignment And Execution

export const SA_SCOPEDETAILS_INIT = 'modules/sa_teamassignmentandexecution/SA_SCOPEDETAILS_INIT';
export const SA_SCOPEDETAILS_LIST_REQUESTED = 'modules/sa_teamassignmentandexecution/SA_SCOPEDETAILS_LIST_REQUESTED';
export const SA_SCOPEDETAILS_LIST_SUCCESS = 'modules/sa_teamassignmentandexecution/SA_SCOPEDETAILS_LIST_SUCCESS';

export const SA_TEAMASSIGNMENTANDEXECUTION_INIT = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_INIT';
export const SA_TEAMASSIGNMENTANDEXECUTION_LIST_REQUESTED = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_LIST_REQUESTED';
export const SA_TEAMASSIGNMENTANDEXECUTION_LIST_SUCCESS = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_LIST_SUCCESS';

export const SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_REQUESTED = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_REQUESTED';
export const SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_SUCCESS = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_SUCCESS';
export const SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_ERROR = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_GET_BY_ID_ERROR';

export const SA_TEAMASSIGNMENTANDEXECUTION_DELETE_REQUESTED = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_DELETE_REQUESTED';
export const SA_TEAMASSIGNMENTANDEXECUTION_DELETE_SUCCESS = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_DELETE_SUCCESS';
export const SA_TEAMASSIGNMENTANDEXECUTION_DELETE_ERROR = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_DELETE_ERROR';

export const SA_TEAMASSIGNMENTANDEXECUTION_SAVE_REQUESTED = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_SAVE_REQUESTED';
export const SA_TEAMASSIGNMENTANDEXECUTION_SAVE_SUCCESS = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_SAVE_SUCCESS';
export const SA_TEAMASSIGNMENTANDEXECUTION_SAVE_ERROR = 'modules/sa_teamassignmentandexecution/SA_TEAMASSIGNMENTANDEXECUTION_SAVE_ERROR';

//#endregion

//#region  Final Audit Plan Execution

export const FINALAUDITPLANEXECUTIONDETALS_INIT = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_INIT';
export const FINALAUDITPLANEXECUTIONDETALS_LIST_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_LIST_REQUESTED';
export const FINALAUDITPLANEXECUTIONDETALS_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_LIST_SUCCESS';
export const FINALAUDITPLANDETALSFOREXECUTION_LIST_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANDETALSFOREXECUTION_LIST_REQUESTED';
export const FINALAUDITPLANDETALSFOREXECUTION_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANDETALSFOREXECUTION_LIST_SUCCESS';
export const FINALAUDITSCOPEDETALSFOREXECUTION_LIST_REQUESTED = 'modules/finalauditplan/FINALAUDITSCOPEDETALSFOREXECUTION_LIST_REQUESTED';
export const FINALAUDITSCOPEDETALSFOREXECUTION_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITSCOPEDETALSFOREXECUTION_LIST_SUCCESS';

export const FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_REQUESTED';
export const FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_SUCCESS';
export const FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_ERROR = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_GET_BY_ID_ERROR';

export const FINALAUDITPLANEXECUTIONDETALS_DELETE_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_DELETE_REQUESTED';
export const FINALAUDITPLANEXECUTIONDETALS_DELETE_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_DELETE_SUCCESS';
export const FINALAUDITPLANEXECUTIONDETALS_DELETE_ERROR = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_DELETE_ERROR';

export const FINALAUDITPLANEXECUTIONDETALS_SAVE_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_SAVE_REQUESTED';
export const FINALAUDITPLANEXECUTIONDETALS_SAVE_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_SAVE_SUCCESS';
export const FINALAUDITPLANEXECUTIONDETALS_SAVE_ERROR = 'modules/finalauditplan/FINALAUDITPLANEXECUTIONDETALS_SAVE_ERROR';

//#endregion


//#region Self Audit Details Process Flow Wise
export const FINALAUDITDETAILS_RESPONSIBILITYWISE_INIT = 'modules/finalaudit/FINALAUDITDETAILS_RESPONSIBILITYWISE_INIT';
export const FINALAUDITDETAILS_RESPONSIBILITYWISE_LIST_REQUESTED = 'modules/finalaudit/FINALAUDITDETAILS_RESPONSIBILITYWISE_LIST_REQUESTED';
export const FINALAUDITDETAILS_RESPONSIBILITYWISE_LIST_SUCCESS = 'modules/finalaudit/FINALAUDITDETAILS_RESPONSIBILITYWISE_LIST_SUCCESS';

//#endregion

//#region  Final Audit planing
export const FINALAUDITPLANDETAILS_INIT = 'modules/finalauditplan/FINALAUDITPLANDETAILS_INIT';
export const FINALAUDITPLANDETAILS_LIST_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANDETAILS_LIST_REQUESTED';
export const FINALAUDITPLANDETAILS_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANDETAILS_LIST_SUCCESS';

export const FINALAUDITPLANDETAILS_GET_BY_ID_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANDETAILS_GET_BY_ID_REQUESTED';
export const FINALAUDITPLANDETAILS_GET_BY_ID_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANDETAILS_GET_BY_ID_SUCCESS';
export const FINALAUDITPLANDETAILS_GET_BY_ID_ERROR = 'modules/finalauditplan/FINALAUDITPLANDETAILS_GET_BY_ID_ERROR';

export const FINALAUDITPLANDETAILS_DELETE_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANDETAILS_DELETE_REQUESTED';
export const FINALAUDITPLANDETAILS_DELETE_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANDETAILS_DELETE_SUCCESS';
export const FINALAUDITPLANDETAILS_DELETE_ERROR = 'modules/finalauditplan/FINALAUDITPLANDETAILS_DELETE_ERROR';

export const FINALAUDITPLANDETAILS_SAVE_REQUESTED = 'modules/finalauditplan/FINALAUDITPLANDETAILS_SAVE_REQUESTED';
export const FINALAUDITPLANDETAILS_SAVE_SUCCESS = 'modules/finalauditplan/FINALAUDITPLANDETAILS_SAVE_SUCCESS';
export const FINALAUDITPLANDETAILS_SAVE_ERROR = 'modules/finalauditplan/FINALAUDITPLANDETAILS_SAVE_ERROR';
export const FINALAUDITSCORE_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITSCORE_LIST_SUCCESS';
//#endregion

//#region  Section Master Details For Final Audit Planning
export const SECTIONDETAILSFORFINALAUDIT_INIT = 'modules/finalauditplan/SECTIONDETAILSFORFINALAUDIT_INIT';
export const SECTIONDETAILSFORFINALAUDIT_LIST_REQUESTED = 'modules/finalauditplan/SECTIONDETAILSFORFINALAUDIT_LIST_REQUESTED';
export const SECTIONDETAILSFORFINALAUDIT_LIST_SUCCESS = 'modules/finalauditplan/SECTIONDETAILSFORFINALAUDIT_LIST_SUCCESS';

//#endregion

//#region  Final Audit Action Plan 
export const FINALAUDITACTIONPLANDETAILS_INIT = 'modules/finalauditplan/FINALAUDITACTIONPLANDETAILS_INIT';
export const FINALAUDITACTIONPLANDETAILS_LIST_REQUESTED = 'modules/finalauditplan/FINALAUDITACTIONPLANDETAILS_LIST_REQUESTED';
export const FINALAUDITACTIONPLANDETAILS_LIST_SUCCESS = 'modules/finalauditplan/FINALAUDITACTIONPLANDETAILS_LIST_SUCCESS';

//#endregion


//#region  Action Plan Update 
export const ACTIONPLANUPDATE_INIT = 'modules/actionplanupdate/ACTIONPLANUPDATE_INIT';
 
export const ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_INIT = 'modules/actionplanupdate/ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_INIT';
export const ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_LIST_REQUESTED = 'modules/actionplanupdate/ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_LIST_REQUESTED';
export const ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_LIST_SUCCESS = 'modules/actionplanupdate/ACTIONPLANUPDATE_ACTIONREQUIREDOBSERVATION_LIST_SUCCESS';
 
export const ACTIONPLANUPDATE_SAVE_REQUESTED = 'modules/actionplanupdate/ACTIONPLANUPDATE_SAVE_REQUESTED';
export const ACTIONPLANUPDATE_SAVE_SUCCESS = 'modules/actionplanupdate/ACTIONPLANUPDATE_SAVE_SUCCESS';
export const ACTIONPLANUPDATE_SAVE_ERROR = 'modules/actionplanupdate/ACTIONPLANUPDATE_SAVE_ERROR';

export const ACTIONPLANUPDATE_LIST_REQUESTED = 'modules/actionplanupdate/ACTIONPLANUPDATE_LIST_REQUESTED';
export const ACTIONPLANUPDATE_LIST_SUCCESS = 'modules/actionplanupdate/ACTIONPLANUPDATE_LIST_SUCCESS';
 
//#endregion


//#region  Monlty Plan Review
export const MONTHLYREVIEW_INIT = 'modules/monthlyreview/ACTIONPLANUPDATE_INIT';
 
export const MONTHLYREVIEW_ACTIONPLANS_INIT = 'modules/monthlyreview/MONTHLYREVIEW_ACTIONPLANS_INIT';
export const MONTHLYREVIEW_ACTIONPLANS_LIST_REQUESTED = 'modules/monthlyreview/MONTHLYREVIEW_ACTIONPLANS_LIST_REQUESTED';
export const MONTHLYREVIEW_ACTIONPLANS_LIST_SUCCESS = 'modules/monthlyreview/MONTHLYREVIEW_ACTIONPLANS_LIST_SUCCESS';
 
export const MONTHLYREVIEW_SAVE_REQUESTED = 'modules/monthlyreview/ACTIONPLANUPDATE_SAVE_REQUESTED';
export const MONTHLYREVIEW_SAVE_SUCCESS = 'modules/monthlyreview/ACTIONPLANUPDATE_SAVE_SUCCESS';
export const MONTHLYREVIEW_SAVE_ERROR = 'modules/monthlyreview/ACTIONPLANUPDATE_SAVE_ERROR';

export const MONTHLYREVIEW_LIST_REQUESTED = 'modules/monthlyreview/ACTIONPLANUPDATE_LIST_REQUESTED';
export const MONTHLYREVIEW_LIST_SUCCESS = 'modules/monthlyreview/ACTIONPLANUPDATE_LIST_SUCCESS';

export const CURRENTMONTH_MONTHLYREVIEW_LIST_SUCCESS = 'modules/monthlyreview/CURRENTMONTH_MONTHLYREVIEW_LIST_SUCCESS';

export const MONTHLYREVIEWDETAILS_INIT = 'modules/monthlyreview/MONTHLYREVIEWDETAILS_INIT';
export const MONTHLYREVIEWDETAILS_LIST_REQUESTED = 'modules/monthlyreview/MONTHLYREVIEWDETAILS_LIST_REQUESTED';
export const MONTHLYREVIEWDETAILS_LIST_SUCCESS = 'modules/monthlyreview/MONTHLYREVIEWDETAILS_LIST_SUCCESS';
//#endregion
