//#region  Final Audit Action Plan 

export const ANTENNAROTATIONDETAILS_INIT = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_INIT';
export const ANTENNAROTATIONDETAILS_LIST_REQUESTED = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_LIST_REQUESTED';
export const ANTENNAROTATIONDETAILS_LIST_SUCCESS = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_LIST_SUCCESS';

export const ANTENNAROTATIONDETAILS_SAVE_REQUESTED = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_SAVE_REQUESTED';
export const ANTENNAROTATIONDETAILS_SAVE_SUCCESS = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_SAVE_SUCCESS';
export const ANTENNAROTATIONDETAILS_SAVE_ERROR = 'modules/antennaRotationDetails/ANTENNAROTATIONDETAILS_SAVE_ERROR';
//#endregion


