export const MASTERDETAILS_INIT = 'modules/masterdetails/MASTERDETAILS_INIT';
export const MASTERDETAILS_LIST_REQUESTED = 'modules/masterdetails/MASTERDETAILS_LIST_REQUESTED';
export const MASTERDETAILS_LIST_SUCCESS = 'modules/masterdetails/MASTERDETAILS_LIST_SUCCESS';

export const MASTERDETAILS_GET_BY_ID_REQUESTED = 'modules/masterdetails/MASTERDETAILS_GET_BY_ID_REQUESTED';
export const MASTERDETAILS_GET_BY_ID_SUCCESS = 'modules/masterdetails/MASTERDETAILS_GET_BY_ID_SUCCESS';
export const MASTERDETAILS_GET_BY_ID_ERROR = 'modules/masterdetails/MASTERDETAILS_GET_BY_ID_ERROR';


export const MASTERDETAILS_MASTERCATEGORYID_INIT = 'modules/masterdetails/MASTERDETAILS_MASTERCATEGORYID_INIT';
export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_REQUESTED = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_REQUESTED';
export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_SUCCESS = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_SUCCESS';
export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_ERROR = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_ERROR';


export const MASTERDETAILS_DELETE_REQUESTED = 'modules/masterdetails/MASTERDETAILS_DELETE_REQUESTED';
export const MASTERDETAILS_DELETE_SUCCESS = 'modules/masterdetails/MASTERDETAILS_DELETE_SUCCESS';
export const MASTERDETAILS_DELETE_ERROR = 'modules/masterdetails/MASTERDETAILS_DELETE_ERROR';

export const MASTERDETAILS_SAVE_REQUESTED = 'modules/masterdetails/MASTERDETAILS_SAVE_REQUESTED';
export const MASTERDETAILS_SAVE_SUCCESS = 'modules/masterdetails/MASTERDETAILS_SAVE_SUCCESS';
export const MASTERDETAILS_SAVE_ERROR = 'modules/masterdetails/MASTERDETAILS_SAVE_ERROR';

//export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_REQUESTED = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_REQUESTED';
//export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_SUCCESS = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_SUCCESS';
//export const MASTERDETAILS_GET_BY_MASTERCATEGORYID_ERROR = 'modules/masterdetails/MASTERDETAILS_GET_BY_MASTERCATEGORYID_ERROR';
