//#region  Tower Monitoring Details

export const DEVICEBATTERYSTATUS_INIT = 'modules/towermonitoring/DEVICEBATTERYSTATUS_INIT';
export const DEVICEBATTERYSTATUS_LIST_REQUESTED = 'modules/towermonitoring/DEVICEBATTERYSTATUS_LIST_REQUESTED';
export const DEVICEBATTERYSTATUS_LIST_SUCCESS = 'modules/towermonitoring/DEVICEBATTERYSTATUS_LIST_SUCCESS';

export const TOWERMONITORINGDETAILS_INIT = 'modules/towermonitoring/TOWERMONITORINGDETAILS_INIT';
export const TOWERMONITORINGDETAILS_LIST_REQUESTED = 'modules/towermonitoring/TOWERMONITORINGDETAILS_LIST_REQUESTED';
export const TOWERMONITORINGDETAILS_LIST_SUCCESS = 'modules/towermonitoring/TOWERMONITORINGDETAILS_LIST_SUCCESS';
 
export const DEVICESTATUSDETAILS_INIT = 'modules/towermonitoring/DEVICESTATUSDETAILS_INIT';
export const DEVICESTATUSDETAILS_LIST_REQUESTED = 'modules/towermonitoring/DEVICESTATUSDETAILS_LIST_REQUESTED';
export const DEVICESTATUSDETAILS_LIST_SUCCESS = 'modules/towermonitoring/DEVICESTATUSDETAILS_LIST_SUCCESS';

export const NETWORKCONNECTIVITYSTATUSDETAILS_INIT = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_INIT';
export const NETWORKCONNECTIVITYSTATUSDETAILS_LIST_REQUESTED = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_LIST_REQUESTED';
export const NETWORKCONNECTIVITYSTATUSDETAILS_LIST_SUCCESS = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_LIST_SUCCESS';
 
export const TOWERMONITORING_SUBDETAILS_INIT = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_INIT';
export const TOWERMONITORING_SUBDETAILS_LIST_REQUESTED = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_LIST_REQUESTED';
export const TOWERMONITORING_SUBDETAILS_LIST_SUCCESS = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_LIST_SUCCESS';
//#endregion
  