//#region  Device mapping details

export const DEVICEMAPPINGDETAILS_INIT = 'modules/deviceMappingDetails/DEVICEMAPPINGDETAILS_INIT';
export const DEVICEMAPPINGDETAILS_LIST_REQUESTED = 'modules/deviceMappingDetails/DEVICEMAPPINGDETAILS_LIST_REQUESTED';
export const DEVICEMAPPINGDETAILS_LIST_SUCCESS = 'modules/deviceMappingDetails/DEVICEMAPPINGDETAILS_LIST_SUCCESS';
 
//#endregion

//#region  Tower Notification Details

export const TOWERNOTIFICATIONDETAILS_INIT = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_INIT';
export const TOWERNOTIFICATIONDETAILS_LIST_REQUESTED = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_LIST_REQUESTED';
export const TOWERNOTIFICATIONDETAILS_LIST_SUCCESS = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_LIST_SUCCESS';
 
export const TOWERNOTIFICATIONDETAILS_SAVE_REQUESTED = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_SAVE_REQUESTED';
export const TOWERNOTIFICATIONDETAILS_SAVE_SUCCESS = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_SAVE_SUCCESS';
export const TOWERNOTIFICATIONDETAILS_SAVE_ERROR = 'modules/towerNotificationDetails/TOWERNOTIFICATIONDETAILS_SAVE_ERROR';

//#endregion
//#region  Tower Monitoring Details

export const DEVICEBATTERYSTATUS_INIT = 'modules/towermonitoring/DEVICEBATTERYSTATUS_INIT';
export const DEVICEBATTERYSTATUS_LIST_REQUESTED = 'modules/towermonitoring/DEVICEBATTERYSTATUS_LIST_REQUESTED';
export const DEVICEBATTERYSTATUS_LIST_SUCCESS = 'modules/towermonitoring/DEVICEBATTERYSTATUS_LIST_SUCCESS';

export const DEVICEBATTERYSTATUSLOG_INIT = 'modules/towermonitoring/DEVICEBATTERYSTATUSLOG_INIT';
export const DEVICEBATTERYSTATUSLOG_LIST_REQUESTED = 'modules/towermonitoring/DEVICEBATTERYSTATUSLOG_LIST_REQUESTED';
export const DEVICEBATTERYSTATUSLOG_LIST_SUCCESS = 'modules/towermonitoring/DEVICEBATTERYSTATUSLOG_LIST_SUCCESS';

export const TOWERMONITORINGDETAILS_INIT = 'modules/towermonitoring/TOWERMONITORINGDETAILS_INIT';
export const TOWERMONITORINGDETAILS_LIST_REQUESTED = 'modules/towermonitoring/TOWERMONITORINGDETAILS_LIST_REQUESTED';
export const TOWERMONITORINGDETAILS_LIST_SUCCESS = 'modules/towermonitoring/TOWERMONITORINGDETAILS_LIST_SUCCESS';
 
export const DEVICESTATUSDETAILS_INIT = 'modules/towermonitoring/DEVICESTATUSDETAILS_INIT';
export const DEVICESTATUSDETAILS_LIST_REQUESTED = 'modules/towermonitoring/DEVICESTATUSDETAILS_LIST_REQUESTED';
export const DEVICESTATUSDETAILS_LIST_SUCCESS = 'modules/towermonitoring/DEVICESTATUSDETAILS_LIST_SUCCESS';

export const NETWORKCONNECTIVITYSTATUSDETAILS_INIT = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_INIT';
export const NETWORKCONNECTIVITYSTATUSDETAILS_LIST_REQUESTED = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_LIST_REQUESTED';
export const NETWORKCONNECTIVITYSTATUSDETAILS_LIST_SUCCESS = 'modules/towermonitoring/NETWORKCONNECTIVITYSTATUSDETAILS_LIST_SUCCESS';
 
export const TOWERMONITORING_SUBDETAILS_INIT = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_INIT';
export const TOWERMONITORING_SUBDETAILS_LIST_REQUESTED = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_LIST_REQUESTED';
export const TOWERMONITORING_SUBDETAILS_LIST_SUCCESS = 'modules/towermonitoring/TOWERMONITORING_SUBDETAILS_LIST_SUCCESS';
//#endregion
  